name: 'CI/CD for Lambda backend code deployment'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'lambdas/**'

jobs:
  deploy:
    name: 'Deploy Lambda Functions'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Install Dependencies
      run: pip install boto3 simplejson

    - name: Package Lambda Functions
      run: |
        mkdir -p lambdas/packages
        for FILE in lambdas/*.py; do
            FUNCTION_NAME=$(basename "${FILE%.*}")
            zip -r lambdas/packages/${FUNCTION_NAME}.zip ${FILE}
        done

    - name: Deploy Lambda Functions
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
      run: |
        for FILE in lambdas/packages/*.zip; do
            FUNCTION_NAME=$(basename "${FILE%.*}")
            aws lambda update-function-code \
              --function-name ${FUNCTION_NAME} \
              --zip-file fileb://${FILE} \
              --region $AWS_REGION
        done
