name: 'CI/CD for Terraform and data injection in the main branch'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'terraform/**'
      - 'scripts/**'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-central-1'
        
    - name: Terraform Init
      run: |
        cd terraform 
        terraform init
      
    - name: Terraform Format
      run: |
        cd terraform
        terraform fmt

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -input=false

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -input=false

  data_injection:
    name: 'Data injection to DynamoDB'
    runs-on: ubuntu-latest
    needs: terraform

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@4

    - name: Setup python
      uses: actions/setup-python@5
      with:
        python-version: '3.12'

    - name: Setup boto3
      run: pip install boto3

    - name: Run data injection script
      run: |
        cd scripts  
        python3 data_injection.py


      