name: 'CI for Terraform in dev branch'

on:
  push:
    branches: [ 'dev' ]
    paths: [ 'terraform/**' ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-central-1'
        
    - name: Terraform Init
      run: |
        cd terraform 
        terraform init
      
    - name: Terraform Format
      run: |
        cd terraform
        terraform fmt

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -input=false
