name: 'CD for website files in main branch'

on:
  push:
    branches: 
      - 'main'
    paths: 
      - 'vue-website/**'

jobs:
  website:
    name: 'Website deployment'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Set up Terraform CLI
      uses: hashicorp/setup-terraform@v3
    
    - name: Terraform init
      run: |
        cd terraform
        terraform init  

    - name: Install dependencies 
      run: | 
       cd vue-website
       npm install

    - name: Build website
      run: |
        cd vue-website
        npm run tailwindbuild
        npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-central-1'

    - name: Deploy to S3 bucket 
      run: |
        cd vue-website
        aws s3 sync dist/ s3://nknez.tech/ --delete --region eu-central-1

    - name: Fetch CloudFront distribution ID from Terraform output
      run: echo "cloudfront_id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV

    - name: Invalidate CloudFront cache
      run: |
        cd terraform
        aws cloudfront create-invalidation --distribution-id ${{ env.cloudfront_id }} --paths "/*"

